//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioMessangerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehiclesDetail
    {
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public string VehicleNumber { get; set; }
        public string LastLongitude { get; set; }
        public string LastLatitude { get; set; }
        public string Altitude { get; set; }
        public string Course { get; set; }
        public string Speed { get; set; }
        public string DriverName { get; set; }
        public string PickUp { get; set; }
        public string Drop { get; set; }
        public string CurrentLongitude { get; set; }
        public string CurrentLatitude { get; set; }
    }
}
