#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TransitApp.Droid.Resource", IsApplication=true)]

namespace TransitApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::TransitApp.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::TransitApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::TransitApp.Droid.Resource.String.Hello;
			global::Acr.XamForms.SignaturePad.Droid.Resource.Id.btnCancel = global::TransitApp.Droid.Resource.Id.btnCancel;
			global::Acr.XamForms.SignaturePad.Droid.Resource.Id.btnSave = global::TransitApp.Droid.Resource.Id.btnSave;
			global::Acr.XamForms.SignaturePad.Droid.Resource.Id.rootView = global::TransitApp.Droid.Resource.Id.rootView;
			global::Acr.XamForms.SignaturePad.Droid.Resource.Id.signatureView = global::TransitApp.Droid.Resource.Id.signatureView;
			global::Acr.XamForms.SignaturePad.Droid.Resource.Layout.SignaturePad = global::TransitApp.Droid.Resource.Layout.SignaturePad;
			global::Acr.XamForms.SignaturePad.Droid.Resource.String.ApplicationName = global::TransitApp.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.SignaturePad.Droid.Resource.String.Hello = global::TransitApp.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public const int Fare_array = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int FuelType_array = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int Status_array = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Tickets_array = 2131165186;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blurbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int breaks = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int brodcasts = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bttncall = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bttnreportstatus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bttnschedule = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bydates = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int calendar = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int calendars = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int call = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int call_small_btn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int change = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int checkbox = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int checkboxselector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int @checked = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_full_open_on_phone = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_ic_googleplayservices = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_disabled_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_disabled_focus_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_disabled_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_focus_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_focus_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_normal_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_normal_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_pressed_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_pressed_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_disabled_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_disabled_focus_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_disabled_focus_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_disabled_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_focus_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_focus_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_normal_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_normal_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_pressed_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_pressed_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int darkbg = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int driverinfos = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int drop = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int edittextborder = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int edittextmobile = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int edittextmsg = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int edittextroundrectangle = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int edittextuser = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int email = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int forma = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int fulereports = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int greenbttn = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_launcher = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_plusone_medium_off_client = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_plusone_small_off_client = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_plusone_standard_off_client = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_plusone_tall_off_client = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int icon = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int lightbg = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int location = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int loginbutton = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int logo = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int logouts = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int monoandroidsplash = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int myprofile = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int myprofiles = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int none = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int pickup = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int profileima = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int RadioOffButton = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int RadioOnButton = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int recode = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int roundrectanglebutton = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int schedule = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int schedule2 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int schedulebutton = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int selected = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int side_menu = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int starts = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int stops = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int user = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int userprofileimage = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int viewdetailss = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int walkietalkie = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int walkietalkies = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int walktalks = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int yellowtitle = 2130837592;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090007
			public const int Breaktimetitle = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f09007b
			public const int backimage = 2131296379;
			
			// aapt resource value: 0x7f090016
			public const int btnCall = 2131296278;
			
			// aapt resource value: 0x7f09008f
			public const int btnCalls = 2131296399;
			
			// aapt resource value: 0x7f090078
			public const int btnCancel = 2131296376;
			
			// aapt resource value: 0x7f090036
			public const int btnLogin = 2131296310;
			
			// aapt resource value: 0x7f090033
			public const int btnRememberUsername = 2131296307;
			
			// aapt resource value: 0x7f090079
			public const int btnSave = 2131296377;
			
			// aapt resource value: 0x7f090015
			public const int btnSchedule = 2131296277;
			
			// aapt resource value: 0x7f090044
			public const int btnSignature = 2131296324;
			
			// aapt resource value: 0x7f090034
			public const int btnStagingServer = 2131296308;
			
			// aapt resource value: 0x7f090025
			public const int btnSubmit = 2131296293;
			
			// aapt resource value: 0x7f090066
			public const int btncalling = 2131296358;
			
			// aapt resource value: 0x7f090090
			public const int btnselectvehicle = 2131296400;
			
			// aapt resource value: 0x7f090067
			public const int btnviewschedule = 2131296359;
			
			// aapt resource value: 0x7f090010
			public const int bttnbroadcast = 2131296272;
			
			// aapt resource value: 0x7f090088
			public const int bttncall = 2131296392;
			
			// aapt resource value: 0x7f090012
			public const int bttndriverinfo = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int bttnmyprofile = 2131296273;
			
			// aapt resource value: 0x7f090065
			public const int bttnreportstatus = 2131296357;
			
			// aapt resource value: 0x7f090089
			public const int bttnschedule = 2131296393;
			
			// aapt resource value: 0x7f090087
			public const int bttnupdate = 2131296391;
			
			// aapt resource value: 0x7f090004
			public const int callimagell = 2131296260;
			
			// aapt resource value: 0x7f09007f
			public const int callingback = 2131296383;
			
			// aapt resource value: 0x7f090080
			public const int callingheading = 2131296384;
			
			// aapt resource value: 0x7f090003
			public const int callingtitle = 2131296259;
			
			// aapt resource value: 0x7f090028
			public const int datepicker = 2131296296;
			
			// aapt resource value: 0x7f09000d
			public const int driverstitle = 2131296269;
			
			// aapt resource value: 0x7f090040
			public const int edittextamount = 2131296320;
			
			// aapt resource value: 0x7f09002f
			public const int edittextll = 2131296303;
			
			// aapt resource value: 0x7f090042
			public const int edittextnote = 2131296322;
			
			// aapt resource value: 0x7f090024
			public const int edittxtAmount = 2131296292;
			
			// aapt resource value: 0x7f090022
			public const int edittxtQuantity = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int edittxtReciept = 2131296289;
			
			// aapt resource value: 0x7f09003e
			public const int edittxtTime = 2131296318;
			
			// aapt resource value: 0x7f090023
			public const int edittxtUnitprice = 2131296291;
			
			// aapt resource value: 0x7f090020
			public const int edittxtfuletype = 2131296288;
			
			// aapt resource value: 0x7f090086
			public const int edittxtmobile = 2131296390;
			
			// aapt resource value: 0x7f090085
			public const int edittxtmsg = 2131296389;
			
			// aapt resource value: 0x7f09003c
			public const int edittxtodo = 2131296316;
			
			// aapt resource value: 0x7f09001d
			public const int edittxtodo1 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int edittxtodo2 = 2131296286;
			
			// aapt resource value: 0x7f09001b
			public const int edittxttime = 2131296283;
			
			// aapt resource value: 0x7f090084
			public const int edittxtuser = 2131296388;
			
			// aapt resource value: 0x7f090017
			public const int fullreport = 2131296279;
			
			// aapt resource value: 0x7f09007e
			public const int image = 2131296382;
			
			// aapt resource value: 0x7f090082
			public const int imagell = 2131296386;
			
			// aapt resource value: 0x7f090014
			public const int imgOnline = 2131296276;
			
			// aapt resource value: 0x7f090005
			public const int imgcall = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int imgcalling = 2131296268;
			
			// aapt resource value: 0x7f09002d
			public const int imgll = 2131296301;
			
			// aapt resource value: 0x7f09008b
			public const int imgnone = 2131296395;
			
			// aapt resource value: 0x7f09004e
			public const int imgpickup = 2131296334;
			
			// aapt resource value: 0x7f090037
			public const int imgvIcon = 2131296311;
			
			// aapt resource value: 0x7f09002e
			public const int imgviewlogin = 2131296302;
			
			// aapt resource value: 0x7f090083
			public const int imgviewuserprofile = 2131296387;
			
			// aapt resource value: 0x7f09008c
			public const int include = 2131296396;
			
			// aapt resource value: 0x7f090091
			public const int linear = 2131296401;
			
			// aapt resource value: 0x7f09000e
			public const int linearlayout2 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int listviewdriver = 2131296271;
			
			// aapt resource value: 0x7f09002a
			public const int llLoadSchedule = 2131296298;
			
			// aapt resource value: 0x7f090064
			public const int llbtnreport = 2131296356;
			
			// aapt resource value: 0x7f090048
			public const int llcall = 2131296328;
			
			// aapt resource value: 0x7f090032
			public const int llcheckbox = 2131296306;
			
			// aapt resource value: 0x7f090053
			public const int lldetail = 2131296339;
			
			// aapt resource value: 0x7f090019
			public const int lldetailfulereport = 2131296281;
			
			// aapt resource value: 0x7f090039
			public const int lldetailreportstatus = 2131296313;
			
			// aapt resource value: 0x7f090046
			public const int llfootermyschedule = 2131296326;
			
			// aapt resource value: 0x7f09008d
			public const int llfootervehicle = 2131296397;
			
			// aapt resource value: 0x7f090074
			public const int llgetsignature = 2131296372;
			
			// aapt resource value: 0x7f090027
			public const int llimageview = 2131296295;
			
			// aapt resource value: 0x7f090035
			public const int llloginbttn = 2131296309;
			
			// aapt resource value: 0x7f090072
			public const int llsave = 2131296370;
			
			// aapt resource value: 0x7f090068
			public const int loginStatus = 2131296360;
			
			// aapt resource value: 0x7f09008e
			public const int lv_VehicleList = 2131296398;
			
			// aapt resource value: 0x7f090047
			public const int lvschedulelist = 2131296327;
			
			// aapt resource value: 0x7f09004c
			public const int myschedulereporttitle = 2131296332;
			
			// aapt resource value: 0x7f090045
			public const int myscheduletitle = 2131296325;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090018
			public const int rldetail = 2131296280;
			
			// aapt resource value: 0x7f090038
			public const int rlreportstatusdetail = 2131296312;
			
			// aapt resource value: 0x7f090076
			public const int rootView = 2131296374;
			
			// aapt resource value: 0x7f090077
			public const int signatureView = 2131296375;
			
			// aapt resource value: 0x7f090029
			public const int signaturepadfooter = 2131296297;
			
			// aapt resource value: 0x7f090026
			public const int signaturepadtitle = 2131296294;
			
			// aapt resource value: 0x7f090041
			public const int spinnerFare = 2131296321;
			
			// aapt resource value: 0x7f090043
			public const int spinnerTeckets = 2131296323;
			
			// aapt resource value: 0x7f09007a
			public const int spinnerText = 2131296378;
			
			// aapt resource value: 0x7f09003b
			public const int spinnerstatus = 2131296315;
			
			// aapt resource value: 0x7f09000a
			public const int startBtn = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int stopBtn = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int text1 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int text2 = 2131296265;
			
			// aapt resource value: 0x7f09004f
			public const int textdetail = 2131296335;
			
			// aapt resource value: 0x7f09004d
			public const int textimagell = 2131296333;
			
			// aapt resource value: 0x7f09002c
			public const int titlelogin = 2131296300;
			
			// aapt resource value: 0x7f09006f
			public const int tvAds = 2131296367;
			
			// aapt resource value: 0x7f09006e
			public const int tvApntTime = 2131296366;
			
			// aapt resource value: 0x7f090070
			public const int tvCarName = 2131296368;
			
			// aapt resource value: 0x7f09006c
			public const int tvCustomerName = 2131296364;
			
			// aapt resource value: 0x7f090071
			public const int tvDeal = 2131296369;
			
			// aapt resource value: 0x7f090069
			public const int tvDepartureTime = 2131296361;
			
			// aapt resource value: 0x7f09006a
			public const int tvDepartureTime2 = 2131296362;
			
			// aapt resource value: 0x7f090006
			public const int tvDrivername = 2131296262;
			
			// aapt resource value: 0x7f09006d
			public const int tvHidden = 2131296365;
			
			// aapt resource value: 0x7f09006b
			public const int tvModifiedDate = 2131296363;
			
			// aapt resource value: 0x7f09004a
			public const int tvRefresh = 2131296330;
			
			// aapt resource value: 0x7f090013
			public const int tvUserName = 2131296275;
			
			// aapt resource value: 0x7f09008a
			public const int tvVehiclename = 2131296394;
			
			// aapt resource value: 0x7f09007d
			public const int tvbreak = 2131296381;
			
			// aapt resource value: 0x7f09004b
			public const int tvrefresh = 2131296331;
			
			// aapt resource value: 0x7f09007c
			public const int tvtitle = 2131296380;
			
			// aapt resource value: 0x7f090051
			public const int txtAddress = 2131296337;
			
			// aapt resource value: 0x7f09002b
			public const int txtLoadSchedule = 2131296299;
			
			// aapt resource value: 0x7f090031
			public const int txtPassword = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int txtUsername = 2131296304;
			
			// aapt resource value: 0x7f09003f
			public const int txtamount = 2131296319;
			
			// aapt resource value: 0x7f09005a
			public const int txtappoinmenttime = 2131296346;
			
			// aapt resource value: 0x7f09005b
			public const int txtappoinmenttimenumber = 2131296347;
			
			// aapt resource value: 0x7f09005c
			public const int txtbrokerauth = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int txtbrokerauthnumber = 2131296349;
			
			// aapt resource value: 0x7f09005e
			public const int txtbrokermileage = 2131296350;
			
			// aapt resource value: 0x7f09005f
			public const int txtbrokermileagenumber = 2131296351;
			
			// aapt resource value: 0x7f090049
			public const int txtcall = 2131296329;
			
			// aapt resource value: 0x7f090060
			public const int txtcompanymileage = 2131296352;
			
			// aapt resource value: 0x7f090061
			public const int txtcompanymileagenumber = 2131296353;
			
			// aapt resource value: 0x7f090050
			public const int txtcustomername = 2131296336;
			
			// aapt resource value: 0x7f090062
			public const int txtdispatch = 2131296354;
			
			// aapt resource value: 0x7f090063
			public const int txtdispatchnumber = 2131296355;
			
			// aapt resource value: 0x7f09001f
			public const int txtfuletype = 2131296287;
			
			// aapt resource value: 0x7f090075
			public const int txtgetsignature = 2131296373;
			
			// aapt resource value: 0x7f090054
			public const int txthome = 2131296340;
			
			// aapt resource value: 0x7f090055
			public const int txthomenumber = 2131296341;
			
			// aapt resource value: 0x7f090056
			public const int txtmobile = 2131296342;
			
			// aapt resource value: 0x7f090057
			public const int txtmobilenumber = 2131296343;
			
			// aapt resource value: 0x7f09001c
			public const int txtodo = 2131296284;
			
			// aapt resource value: 0x7f090073
			public const int txtsave = 2131296371;
			
			// aapt resource value: 0x7f090058
			public const int txtscheduletime = 2131296344;
			
			// aapt resource value: 0x7f090059
			public const int txtscheduletimenumber = 2131296345;
			
			// aapt resource value: 0x7f09003a
			public const int txtstatus = 2131296314;
			
			// aapt resource value: 0x7f09001a
			public const int txttime = 2131296282;
			
			// aapt resource value: 0x7f09003d
			public const int txttimereportsts = 2131296317;
			
			// aapt resource value: 0x7f090092
			public const int txtvehicles = 2131296402;
			
			// aapt resource value: 0x7f090052
			public const int txtwalker = 2131296338;
			
			// aapt resource value: 0x7f090081
			public const int userprofiletitle = 2131296385;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudioCalling = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Break_Time = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DriverList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DriverListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FuleReport = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoadSchedule = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int logintitle = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ReportStatus = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Schedule = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ScheduleDetails = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ScheduleListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Signature = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SignaturePad = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SpinnerItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int titleimagetext = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int titleLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int userProfile = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int VehicleListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int vehicles = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int vehiclestitle = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040046
			public const int Fare_prompt = 2130968646;
			
			// aapt resource value: 0x7f040048
			public const int FuelType_prompt = 2130968648;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040045
			public const int Status_prompt = 2130968645;
			
			// aapt resource value: 0x7f040047
			public const int Tickets_prompt = 2130968647;
			
			// aapt resource value: 0x7f040027
			public const int action_settings = 2130968615;
			
			// aapt resource value: 0x7f040041
			public const int amount = 2130968641;
			
			// aapt resource value: 0x7f040025
			public const int app_name = 2130968613;
			
			// aapt resource value: 0x7f040038
			public const int appoinmenttime = 2130968632;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040039
			public const int brokerauth = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int brokermileage = 2130968634;
			
			// aapt resource value: 0x7f04002d
			public const int calling = 2130968621;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f04003b
			public const int companymileage = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int dispatchnumber = 2130968636;
			
			// aapt resource value: 0x7f040042
			public const int done = 2130968642;
			
			// aapt resource value: 0x7f04002e
			public const int driverlist = 2130968622;
			
			// aapt resource value: 0x7f040034
			public const int fullreport = 2130968628;
			
			// aapt resource value: 0x7f040026
			public const int hello_world = 2130968614;
			
			// aapt resource value: 0x7f040035
			public const int home = 2130968629;
			
			// aapt resource value: 0x7f040024
			public const int library_name = 2130968612;
			
			// aapt resource value: 0x7f04002b
			public const int login = 2130968619;
			
			// aapt resource value: 0x7f040036
			public const int mobile = 2130968630;
			
			// aapt resource value: 0x7f040031
			public const int myprofile = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int myschedule = 2130968626;
			
			// aapt resource value: 0x7f04003f
			public const int odo = 2130968639;
			
			// aapt resource value: 0x7f040029
			public const int rememberusername = 2130968617;
			
			// aapt resource value: 0x7f04003d
			public const int reportstatus = 2130968637;
			
			// aapt resource value: 0x7f040037
			public const int scheduledtime = 2130968631;
			
			// aapt resource value: 0x7f040030
			public const int selectvehicle = 2130968624;
			
			// aapt resource value: 0x7f04002a
			public const int server = 2130968618;
			
			// aapt resource value: 0x7f04003e
			public const int status = 2130968638;
			
			// aapt resource value: 0x7f040040
			public const int time = 2130968640;
			
			// aapt resource value: 0x7f040044
			public const int update = 2130968644;
			
			// aapt resource value: 0x7f040028
			public const int userlogin = 2130968616;
			
			// aapt resource value: 0x7f040043
			public const int userprofile = 2130968643;
			
			// aapt resource value: 0x7f04002c
			public const int vehicles = 2130968620;
			
			// aapt resource value: 0x7f040033
			public const int viewdetails = 2130968627;
			
			// aapt resource value: 0x7f04002f
			public const int viewschedule = 2130968623;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
