//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioMessangerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriverSchedule
    {
        public int UserId { get; set; }
        public int VehicleId { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string DepatureDateTime { get; set; }
        public string AppointmentDateTime { get; set; }
        public string PickupLongitude { get; set; }
        public string PickupLatitude { get; set; }
        public string DropLongilude { get; set; }
        public string DropLatitude { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusDetail { get; set; }
    }
}
