//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioMessangerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleDetail
    {
        public int ScheduleId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string HomeNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ScheduleTime { get; set; }
        public string AppointmentTime { get; set; }
        public string BrokerAuth { get; set; }
        public string BrokerMileage { get; set; }
        public string CompanyMileage { get; set; }
        public string DispatchNumber { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string DepatureDateTime { get; set; }
        public string AppointmentDateTime { get; set; }
        public string PickupLongitude { get; set; }
        public string PickupLatitude { get; set; }
        public string DropLongilude { get; set; }
        public string DropLatitude { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusType { get; set; }
        public string StatusDetail { get; set; }
        public Nullable<double> ODO { get; set; }
        public string Time { get; set; }
        public string Amount { get; set; }
        public string Fare { get; set; }
        public string Note { get; set; }
        public string Tickets { get; set; }
        public byte[] Signature { get; set; }
    }
}
