//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioMessangerApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransitExecEntities : DbContext
    {
        public TransitExecEntities()
            : base("name=TransitExecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblDriverSchedule> tblDriverSchedules { get; set; }
        public DbSet<tblLoginTable> tblLoginTables { get; set; }
        public DbSet<tblScheduleDetail> tblScheduleDetails { get; set; }
        public DbSet<tblVehiclesDetail> tblVehiclesDetails { get; set; }
    }
}
